# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p> 

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from foreman.api.content_view_histories_api import ContentViewHistoriesApi


class TestContentViewHistoriesApi(unittest.TestCase):
    """ContentViewHistoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContentViewHistoriesApi()

    def tearDown(self) -> None:
        pass

    def test_get_content_views_id_history(self) -> None:
        """Test case for get_content_views_id_history

        Show a content view's history
        """
        pass


if __name__ == "__main__":
    unittest.main()
