# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p> 

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from foreman.api.common_parameters_api import CommonParametersApi


class TestCommonParametersApi(unittest.TestCase):
    """CommonParametersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommonParametersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_common_parameters_id(self) -> None:
        """Test case for delete_common_parameters_id

        Delete a global parameter
        """
        pass

    def test_get_common_parameters(self) -> None:
        """Test case for get_common_parameters

        List all global parameters
        """
        pass

    def test_get_common_parameters_id(self) -> None:
        """Test case for get_common_parameters_id

        Show a global parameter
        """
        pass

    def test_post_common_parameters(self) -> None:
        """Test case for post_common_parameters

        Create a global parameter
        """
        pass

    def test_put_common_parameters_id(self) -> None:
        """Test case for put_common_parameters_id

        Update a global parameter
        """
        pass


if __name__ == "__main__":
    unittest.main()
