# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p>   # noqa: E501

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyforeman
from pyforeman.api.template_kinds_api import TemplateKindsApi  # noqa: E501
from pyforeman.rest import ApiException


class TestTemplateKindsApi(unittest.TestCase):
    """TemplateKindsApi unit test stubs"""

    def setUp(self):
        self.api = pyforeman.api.template_kinds_api.TemplateKindsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_template_kinds(self):
        """Test case for get_template_kinds

        List all template kinds  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
