# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p>   # noqa: E501

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyforeman
from pyforeman.api.sync_plans_api import SyncPlansApi  # noqa: E501
from pyforeman.rest import ApiException


class TestSyncPlansApi(unittest.TestCase):
    """SyncPlansApi unit test stubs"""

    def setUp(self):
        self.api = pyforeman.api.sync_plans_api.SyncPlansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_organizations_organization_id_sync_plans_id(self):
        """Test case for delete_organizations_organization_id_sync_plans_id

        Destroy a sync plan  # noqa: E501
        """
        pass

    def test_delete_sync_plans_id(self):
        """Test case for delete_sync_plans_id

        Destroy a sync plan  # noqa: E501
        """
        pass

    def test_get_organizations_organization_id_sync_plans(self):
        """Test case for get_organizations_organization_id_sync_plans"""
        pass

    def test_get_organizations_organization_id_sync_plans_id(self):
        """Test case for get_organizations_organization_id_sync_plans_id

        Show a sync plan  # noqa: E501
        """
        pass

    def test_get_sync_plans(self):
        """Test case for get_sync_plans

        List sync plans  # noqa: E501
        """
        pass

    def test_get_sync_plans_id(self):
        """Test case for get_sync_plans_id

        Show a sync plan  # noqa: E501
        """
        pass

    def test_post_organizations_organization_id_sync_plans(self):
        """Test case for post_organizations_organization_id_sync_plans

        Create a sync plan  # noqa: E501
        """
        pass

    def test_put_organizations_organization_id_sync_plans_id(self):
        """Test case for put_organizations_organization_id_sync_plans_id

        Update a sync plan  # noqa: E501
        """
        pass

    def test_put_organizations_organization_id_sync_plans_id_add_products(self):
        """Test case for put_organizations_organization_id_sync_plans_id_add_products

        Add products to sync plan  # noqa: E501
        """
        pass

    def test_put_organizations_organization_id_sync_plans_id_remove_products(self):
        """Test case for put_organizations_organization_id_sync_plans_id_remove_products

        Remove products from sync plan  # noqa: E501
        """
        pass

    def test_put_organizations_organization_id_sync_plans_id_sync(self):
        """Test case for put_organizations_organization_id_sync_plans_id_sync

        Initiate a sync of the products attached to the sync plan  # noqa: E501
        """
        pass

    def test_put_sync_plans_id(self):
        """Test case for put_sync_plans_id

        Update a sync plan  # noqa: E501
        """
        pass

    def test_put_sync_plans_id_sync(self):
        """Test case for put_sync_plans_id_sync

        Initiate a sync of the products attached to the sync plan  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
