# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p>   # noqa: E501

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyforeman
from pyforeman.api.auth_sources_api import AuthSourcesApi  # noqa: E501
from pyforeman.rest import ApiException


class TestAuthSourcesApi(unittest.TestCase):
    """AuthSourcesApi unit test stubs"""

    def setUp(self):
        self.api = pyforeman.api.auth_sources_api.AuthSourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_auth_sources(self):
        """Test case for get_auth_sources

        List all authentication sources  # noqa: E501
        """
        pass

    def test_get_locations_location_id_auth_sources(self):
        """Test case for get_locations_location_id_auth_sources

        List all authentication sources per location  # noqa: E501
        """
        pass

    def test_get_organizations_organization_id_auth_sources(self):
        """Test case for get_organizations_organization_id_auth_sources

        List all authentication sources per organization  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
