# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p>   # noqa: E501

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyforeman
from pyforeman.api.table_preferences_api import TablePreferencesApi  # noqa: E501
from pyforeman.rest import ApiException


class TestTablePreferencesApi(unittest.TestCase):
    """TablePreferencesApi unit test stubs"""

    def setUp(self):
        self.api = (
            pyforeman.api.table_preferences_api.TablePreferencesApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_users_user_id_table_preferences_name(self):
        """Test case for delete_users_user_id_table_preferences_name

        Delete a table preference for a given table  # noqa: E501
        """
        pass

    def test_get_users_user_id_table_preferences(self):
        """Test case for get_users_user_id_table_preferences

        List of table preferences for a user  # noqa: E501
        """
        pass

    def test_get_users_user_id_table_preferences_name(self):
        """Test case for get_users_user_id_table_preferences_name

        Table preference details of a given table  # noqa: E501
        """
        pass

    def test_post_users_user_id_table_preferences(self):
        """Test case for post_users_user_id_table_preferences

        Creates a table preference for a given table  # noqa: E501
        """
        pass

    def test_put_users_user_id_table_preferences_name(self):
        """Test case for put_users_user_id_table_preferences_name

        Updates a table preference for a given table  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
