# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p> 

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from foreman.api.ansible_collections_api import AnsibleCollectionsApi


class TestAnsibleCollectionsApi(unittest.TestCase):
    """AnsibleCollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnsibleCollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_get_ansible_collections(self) -> None:
        """Test case for get_ansible_collections

        List ansible_collections
        """
        pass

    def test_get_ansible_collections_compare(self) -> None:
        """Test case for get_ansible_collections_compare

        List :resource
        """
        pass

    def test_get_ansible_collections_id(self) -> None:
        """Test case for get_ansible_collections_id

        Show an ansible collection
        """
        pass

    def test_get_content_view_filters_content_view_filter_id_ansible_collections(
        self,
    ) -> None:
        """Test case for get_content_view_filters_content_view_filter_id_ansible_collections

        List ansible_collections
        """
        pass

    def test_get_content_views_content_view_id_filters_filter_id_ansible_collections(
        self,
    ) -> None:
        """Test case for get_content_views_content_view_id_filters_filter_id_ansible_collections

        List ansible_collections
        """
        pass

    def test_get_repositories_repository_id_ansible_collections(self) -> None:
        """Test case for get_repositories_repository_id_ansible_collections

        List ansible_collections
        """
        pass

    def test_get_repositories_repository_id_ansible_collections_id(self) -> None:
        """Test case for get_repositories_repository_id_ansible_collections_id

        Show an ansible collection
        """
        pass


if __name__ == "__main__":
    unittest.main()
