# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p>   # noqa: E501

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyforeman
from pyforeman.api.job_invocations_api import JobInvocationsApi  # noqa: E501
from pyforeman.rest import ApiException


class TestJobInvocationsApi(unittest.TestCase):
    """JobInvocationsApi unit test stubs"""

    def setUp(self):
        self.api = pyforeman.api.job_invocations_api.JobInvocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job_invocations(self):
        """Test case for get_job_invocations

        List job invocations  # noqa: E501
        """
        pass

    def test_get_job_invocations_id(self):
        """Test case for get_job_invocations_id

        Show job invocation  # noqa: E501
        """
        pass

    def test_get_job_invocations_id_hosts_host_id(self):
        """Test case for get_job_invocations_id_hosts_host_id

        Get output for a host  # noqa: E501
        """
        pass

    def test_get_job_invocations_id_hosts_host_id_raw(self):
        """Test case for get_job_invocations_id_hosts_host_id_raw

        Get raw output for a host  # noqa: E501
        """
        pass

    def test_get_job_invocations_id_outputs(self):
        """Test case for get_job_invocations_id_outputs

        Get outputs of hosts in a job  # noqa: E501
        """
        pass

    def test_post_job_invocations(self):
        """Test case for post_job_invocations

        Create a job invocation  # noqa: E501
        """
        pass

    def test_post_job_invocations_id_cancel(self):
        """Test case for post_job_invocations_id_cancel

        Cancel job invocation  # noqa: E501
        """
        pass

    def test_post_job_invocations_id_rerun(self):
        """Test case for post_job_invocations_id_rerun

        Rerun job on failed hosts  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
