# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p>   # noqa: E501

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyforeman
from pyforeman.api.package_groups_api import PackageGroupsApi  # noqa: E501
from pyforeman.rest import ApiException


class TestPackageGroupsApi(unittest.TestCase):
    """PackageGroupsApi unit test stubs"""

    def setUp(self):
        self.api = pyforeman.api.package_groups_api.PackageGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_content_view_filters_content_view_filter_id_package_groups(self):
        """Test case for get_content_view_filters_content_view_filter_id_package_groups

        List package_groups  # noqa: E501
        """
        pass

    def test_get_content_views_content_view_id_filters_filter_id_package_groups(self):
        """Test case for get_content_views_content_view_id_filters_filter_id_package_groups

        List package_groups  # noqa: E501
        """
        pass

    def test_get_package_groups(self):
        """Test case for get_package_groups

        List package_groups  # noqa: E501
        """
        pass

    def test_get_package_groups_compare(self):
        """Test case for get_package_groups_compare

        List package_groups  # noqa: E501
        """
        pass

    def test_get_package_groups_id(self):
        """Test case for get_package_groups_id

        Show a package group  # noqa: E501
        """
        pass

    def test_get_repositories_repository_id_package_groups(self):
        """Test case for get_repositories_repository_id_package_groups

        List package_groups  # noqa: E501
        """
        pass

    def test_get_repositories_repository_id_package_groups_id(self):
        """Test case for get_repositories_repository_id_package_groups_id

        Show a package group  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
