# coding: utf-8

"""
    Foreman (params in:formData)

     <p>Foreman API v2 is currently the default API version.</p>   # noqa: E501

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyforeman
from pyforeman.api.host_subscriptions_api import HostSubscriptionsApi  # noqa: E501
from pyforeman.rest import ApiException


class TestHostSubscriptionsApi(unittest.TestCase):
    """HostSubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = (
            pyforeman.api.host_subscriptions_api.HostSubscriptionsApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_hosts_host_id_subscriptions(self):
        """Test case for delete_hosts_host_id_subscriptions

        Unregister the host as a subscription consumer  # noqa: E501
        """
        pass

    def test_get_hosts_host_id_subscriptions(self):
        """Test case for get_hosts_host_id_subscriptions

        List a host's subscriptions  # noqa: E501
        """
        pass

    def test_get_hosts_host_id_subscriptions_available_release_versions(self):
        """Test case for get_hosts_host_id_subscriptions_available_release_versions

        Show releases available for the content host  # noqa: E501
        """
        pass

    def test_get_hosts_host_id_subscriptions_enabled_repositories(self):
        """Test case for get_hosts_host_id_subscriptions_enabled_repositories

        Show repositories enabled on the host that are known to Katello  # noqa: E501
        """
        pass

    def test_get_hosts_host_id_subscriptions_product_content(self):
        """Test case for get_hosts_host_id_subscriptions_product_content

        Get content and overrides for the host  # noqa: E501
        """
        pass

    def test_post_hosts_subscriptions(self):
        """Test case for post_hosts_subscriptions

        Register a host with subscription and information  # noqa: E501
        """
        pass

    def test_put_hosts_host_id_subscriptions_add_subscriptions(self):
        """Test case for put_hosts_host_id_subscriptions_add_subscriptions

        Add a subscription to a host  # noqa: E501
        """
        pass

    def test_put_hosts_host_id_subscriptions_auto_attach(self):
        """Test case for put_hosts_host_id_subscriptions_auto_attach

        Trigger an auto-attach of subscriptions  # noqa: E501
        """
        pass

    def test_put_hosts_host_id_subscriptions_content_override(self):
        """Test case for put_hosts_host_id_subscriptions_content_override

        Set content overrides for the host  # noqa: E501
        """
        pass

    def test_put_hosts_host_id_subscriptions_remove_subscriptions(self):
        """Test case for put_hosts_host_id_subscriptions_remove_subscriptions"""
        pass


if __name__ == "__main__":
    unittest.main()
